apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statging
  template:
    metadata:
      labels:
        app: statging
    spec:
       rules:  
       - host: staging-guestbook.mstakx.io
       
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80